name: GitHub Actions Google Test
run-name: ${{ github.actor }} is pushing into ${{ github.ref }} 🚀
on:
   pull_request:
     branches: [ master ]
     paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
      - 'TODO.md'
      - 'FAQ.md'
      - '.github/*'
      - '.gitignore'
      - 'src/sandbox/*'
      - 'cgi/*'
      - 'test_files/*'
jobs:
  Perform-Unit-Test:
    runs-on: ubuntu-latest
    steps:
    - name: Install packages
      run: sudo apt-get -y install clang && sudo apt-get -y install cmake
    - uses: actions/checkout@v3
    - name: test make all compiles
      run:  make all
    - name: Build gTest
      run:  make gTest
    - name: Run Test
      run: cd gTest/build && ./runTest
